### ISSUE TITLE
NessieService.getBills() throws exception

### ISSUE THREAD

**Issue by jzarakas** [nessieisreal/nessie-android-sdk#16]
`        nessieClient.getBills("56c66be6a73e492741507f1e", new NessieResultsListener() {
            @Override
            public void onSuccess(Object result, NessieException e) {
                if(e == null){
                    ArrayList<Bill> bills = (ArrayList<Bill>) result;
                    System.out.println("BILLS TEST");
                    System.out.println(bills.size());
                    for(Bill bill:bills){
                        System.out.println(bill.toString());
                    }
                } else {
                    System.out.println(e.toString());
                }
            }
        });
`

Returns

`com.reimaginebanking.api.java.NessieException: No Body Received
	at com.reimaginebanking.api.java.NessieClient$9.failure(NessieClient.java:170)
	at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
	at retrofit.Utils$SynchronousExecutor.execute(Utils.java:114)
	at retrofit.CallbackRunnable.run(CallbackRunnable.java:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at retrofit.Platform$Base$2$1.run(Platform.java:94)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by jzarakas** [comment]
I think the issue ties around Gson not deserializing as expected with Retrofit, but I'm not positive. Using OkHTTP/Gson directly seems to work just fine (pending more testing).
